### ISSUE TITLE
Doomguy's Face in Inventory

### ISSUE THREAD

**Issue by Antinoe** [Antinoe/ZDoom-DwellingSin-Countrycide#2]
There lacks Face Sprites for the Master Templar. Due to this, Doomguy's face shows in the Inventory.

**Comment by DyNaM1Kk** [comment]
The easiest solution would be to crop out Master Templar's face from his sprite. Dwelling Sin only uses STFST01, STFST11, STFST21, STFST31, STFST41, STFGOD0 and STFDEAD0 graphics. You can reuse the single face graphic by making duplicates and renaming them to the names listed above.
