### ISSUE TITLE
Revolver Casing Ejection

### ISSUE THREAD

**Issue by Antinoe** [Antinoe/ZDoom-DwellingSin-Countrycide#4]
Since the Revolver now uses the FIRE_MANUAL SinFireType, casings eject out of the weapon when fired.

**Comment by DyNaM1Kk** [comment]
This can be fixed by passing an empty string to the `Casing` property in the `BulletClip` class.

**Comment by Antinoe** [comment]
A messy fix, but considering Countrycide doesn't have any Pistols, it'll work for now.
